import { describe, expect, it } from 'vitest'
import { GENUI_SYSTEM_PROMPT, genuiSystemPrompt } from '../src/prompt.ts'

describe('GenUI system prompt', () => {
  it('keeps user handoffs product-focused without adding another prompt section', () => {
    expect(GENUI_SYSTEM_PROMPT).toContain('even when the user does not ask for an interface')
    expect(GENUI_SYSTEM_PROMPT).toContain('A direct request for an interactive card, simulator, explorable model, or visual control is explicit intent')
    expect(GENUI_SYSTEM_PROMPT).toContain('Never use workspace file, write, edit, shell, or coding tools to create or stage its source, even temporarily')
    expect(GENUI_SYSTEM_PROMPT).toContain('one focused decision or working surface, not a miniature site or dashboard that repeats the answer')
    expect(GENUI_SYSTEM_PROMPT).toContain('normally 3–5 source files including its stylesheet')
    expect(GENUI_SYSTEM_PROMPT).toContain('Do not create one for ordinary questions, rewriting, summarization, or explanations where interaction does not improve understanding')
    expect(GENUI_SYSTEM_PROMPT).toContain('Do not ask the user to choose a presentation format when the best choice is evident')
    expect(GENUI_SYSTEM_PROMPT).toContain('Keep every genui_* call invisible.')
    expect(GENUI_SYSTEM_PROMPT).toContain('Every visible assistant sentence must be final-answer content, never a work update; fix failures silently.')
    expect(GENUI_SYSTEM_PROMPT).toContain('Harness may expose short reasoning summaries')
    expect(GENUI_SYSTEM_PROMPT).toContain('without narrating tool selection, files, code writing, compilation, verification, or other implementation steps')
    expect(GENUI_SYSTEM_PROMPT).toContain('never create goals, plans, to-dos, recurring work, or workspace files for it')
    expect(GENUI_SYSTEM_PROMPT).toContain('including when the user says they will return later')
    expect(GENUI_SYSTEM_PROMPT).toContain('state the main recommendation in 1–3 natural sentences before the call')
    expect(GENUI_SYSTEM_PROMPT).toContain('For input collection, state what information is still missing in 1–2 sentences')
    expect(GENUI_SYSTEM_PROMPT).toContain('never announce a page or list what it will contain')
    expect(GENUI_SYSTEM_PROMPT).toContain('write the framing prose before the call and put only that part in the card')
    expect(GENUI_SYSTEM_PROMPT).toContain('must be the last emitted item: run no more tools and emit no text after it')
    expect(GENUI_SYSTEM_PROMPT).toContain('Never say the card is ready')
    expect(GENUI_SYSTEM_PROMPT).toContain('never mention GenUI, tools, artifacts, versions, source files, builds, diagnostics, requirement ledgers, device checks, or design profiles')
    expect(GENUI_SYSTEM_PROMPT.indexOf('Keep every genui_* call')).toBeLessThan(GENUI_SYSTEM_PROMPT.indexOf('This is Code First'))
    expect(GENUI_SYSTEM_PROMPT.match(/^## /gm)).toHaveLength(1)
    expect(GENUI_SYSTEM_PROMPT).not.toContain('genui_verify')
    expect(GENUI_SYSTEM_PROMPT).not.toContain('subscribeArtifactState')
    expect(GENUI_SYSTEM_PROMPT).toContain('never retry it with genui_create')
    expect(GENUI_SYSTEM_PROMPT).toContain('use its exact name through callTool even if the same data also has a public API')
    expect(GENUI_SYSTEM_PROMPT).toContain('Use requestExternal only when no matching connected tool exists')
    expect(GENUI_SYSTEM_PROMPT).toContain('For a one-time live fact, the Agent may fetch it first')
    expect(GENUI_SYSTEM_PROMPT).toContain('Never invent or present an unknown venue, price, schedule, availability, weather condition, measurement, or external status as fact')
    expect(GENUI_SYSTEM_PROMPT).toContain('Design the initial Inline view around one primary task and at most two content sections')
    expect(GENUI_SYSTEM_PROMPT).toContain('build a manipulable causal model around the difficult relationship rather than a dashboard')
    expect(GENUI_SYSTEM_PROMPT).toContain('Keep it to one control group, one main visual, and one dynamic takeaway')
    expect(GENUI_SYSTEM_PROMPT).toContain('Use semantic controls with accessible names')
    expect(GENUI_SYSTEM_PROMPT).toContain('genui_state_read must be the first tool call before any answer or action')
    expect(GENUI_SYSTEM_PROMPT).toContain('Use its current values and __result as the authority')
    expect(GENUI_SYSTEM_PROMPT).toContain('never answer from an earlier chat summary or remembered defaults')
    expect(GENUI_SYSTEM_PROMPT).toContain('Use at most one targeted read per requested source')
    expect(GENUI_SYSTEM_PROMPT).toContain('A 429, Retry-After, or an explicit exhausted-quota response is rate limiting')
    expect(GENUI_SYSTEM_PROMPT).toContain('Disable every control that can start the same operation while it is pending')
    expect(GENUI_SYSTEM_PROMPT).toContain('JSON responses must be parsed with JSON.parse(body)')
    expect(GENUI_SYSTEM_PROMPT).toContain('Keep fetched search results, catalogs, and other replaceable response payloads in plain React useState')
    expect(GENUI_SYSTEM_PROMPT).toContain('Derive reload and empty-state copy from data that actually remains available')
  })

  it('honors a Harness default design without changing the automatic default', () => {
    expect(GENUI_SYSTEM_PROMPT).toContain('silently choose and export the best bundled design')
    const custom = genuiSystemPrompt('home-journal')
    expect(custom).toContain('The Harness default design is home-journal')
    expect(custom).toContain('silently export and use it unless the user asks for another direction')
    expect(custom).not.toContain('silently choose and export the best bundled design')
  })
})
